# -*- coding: utf-8 -*-
"""GANs Scratch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gXkrpshydD2hqQ5ObWIcgsOtQ71BrpYi
"""

import torch
import matplotlib.pyplot as plt

# Generator and Discriminator
# Helpers
# Training loop
# Putting everythimg together

# generator and Discriminator
import torch.nn as nn
from tqdm import tqdm
class Generator(nn.Module):
    def __init__(self, input_dimension=100, hidden_dim=1200, output_dimension=28*28):
        super(Generator, self).__init__()
        self.network = nn.Sequential(
            nn.Linear(input_dimension, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, output_dimension),
            nn.Tanh()
        )

    def forward(self, z):
        return self.network(z)


class Discriminator(nn.Module):
    def __init__(self, input_dimension=28*28, hidden_dim=1200, output_dimension=1):
        super(Discriminator,self).__init__()
        self.network = nn.Sequential(
            nn.Linear(input_dimension, hidden_dim),
            nn.LeakyReLU(negative_slope=0.2),
            nn.Linear(hidden_dim, hidden_dim),
            nn.LeakyReLU(0.2),
            nn.Linear(hidden_dim, output_dimension),
            nn.Sigmoid()
        )

    def forward(self, z):
        return self.network(z)

generator=Generator()
z = torch.randn(8,100)
generator(z).shape
x = generator(z)

discrminator = Discriminator()
p = discrminator(x)

p

from keras.datasets.mnist import load_data
import numpy as np

(train_X, trainy),(test_X,testy) = load_data()
train_X = (np.float32(train_X)-127.5)/127.5

# Helpers
def sample_noise(batch_size,latent_size=100, device="cpu"):
  return torch.randn((batch_size,latent_size),device=device)
def sample_minibatch(batch_size, device= "cpu"):
  indices = torch.randperm(train_X.shape[0])[:batch_size]
  return torch.from_numpy(train_X[indices]).to(torch.float).reshape(batch_size,-1).to(device)

def training_loop(generator, discriminator, g_opt, d_opt, nb_epochs, k=1, batch_size=100, device="cpu"):
    loss_fn = nn.BCELoss()
    training_loss = {"generator": [], "discriminator": []}

    for epoch in tqdm(range(nb_epochs)):
        # ---- Train Discriminator ----
        for _ in range(k):
            z = sample_noise(batch_size, device=device)
            x = sample_minibatch(batch_size, device=device)

            fake_pred = discriminator(generator(z).detach()).view(-1)
            real_pred = discriminator(x).view(-1)

            fake_labels = torch.zeros(batch_size).to(device)
            real_labels = torch.ones(batch_size).to(device)

            fake_loss = loss_fn(fake_pred, fake_labels)
            real_loss = loss_fn(real_pred, real_labels)
            d_loss = (fake_loss + real_loss) / 2

            d_opt.zero_grad()
            d_loss.backward()
            d_opt.step()

            training_loss["discriminator"].append(d_loss.item())

        # ---- Train Generator ----
        z = sample_noise(batch_size, device=device)
        g_pred = discriminator(generator(z)).view(-1)
        g_labels = torch.ones(batch_size).to(device)

        g_loss = loss_fn(g_pred, g_labels)
        g_opt.zero_grad()
        g_loss.backward()
        g_opt.step()

        training_loss["generator"].append(g_loss.item())

    return training_loss

sample_noise(100,device="cpu")

sample_minibatch(100,device="cpu")

import torch
import matplotlib.pyplot as plt

with torch.no_grad():
    img = x[3].cpu().numpy()

plt.imshow(img.reshape(28, 28))

# Main
device = 'cuda'
generator = Generator().to(device)
discriminator = Discriminator().to(device)

g_opt = torch.optim.SGD(generator.parameters(), lr=0.1, momentum=0.5)
d_opt = torch.optim.SGD(discriminator.parameters(), lr=0.1, momentum=0.5)

training_loop(generator, discriminator, g_opt, d_opt, 50000, batch_size=100, device=device)

z=sample_noise(1,device=device)
x=generator(z)
print(x.sum())
plt.imshow(x[0].data.cpu().numpy().reshape(28,28),cmap="gray")

NB_IMAGES = 25
z = sample_noise(NB_IMAGES,device=device)
x = generator(z).data.cpu().numpy()
plt.figure(figsize=(17,17))
for i in range(NB_IMAGES):
  plt.subplot(5,5,1+i)
  plt.axis('off')
  plt.imshow(x[i].reshape(28,28),cmap="gray")
plt.savefig('generatedsamples.png')

